# Generated by Django 3.0.7 on 2020-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofa', models.ImageField(default='i1.jpg', upload_to='')),
                ('curtain', models.ImageField(default='i1.jpg', upload_to='')),
            ],
        ),
    ]
